### ISSUE TITLE
The lobster no work.

### ISSUE THREAD

**Issue by 13jon37** [AMATEURZ1337/LobsterOS#1]
No lobsters.

**Comment by AMATEURZ1337** [comment]
Hey! 

That's sad to hear that, you're not satisfacted from out LobsterOS :(
I checked all features of our os and everything is fine, everything is working, so i don't know where is your issue.

Have a nice day :)

**Comment by 13jon37** [comment]
No lobsters, so what's the point?

**Comment by AMATEURZ1337** [comment]
Ok, i will set up wallpaper with lobster , will it be ok?
